name: Deploy to my server
on:
  push:
    branches:
      - main # 或是你部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
            
      - name: Install Dependencies
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm install -g yarn
      - run: yarn
      - run: yarn build

      - name: SSH to server and Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "./.next"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "~/x-future-website"
          SCRIPT_AFTER: |
            cd ~/x-future-website
            pm2 restart app
